spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/localib?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver